icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %b %d %R (%x)"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#32302f"
idle_fg = "#d5c4a1"
info_bg = "#8ec07c"
info_fg = "#32302f"
good_bg = "#b8bb26"
good_fg = "#32302f"
warning_bg = "#fabd2f"
warning_fg = "#32302f"
critical_bg = "#fb4934"
critical_fg = "#32302f"
