require 'rake/clean'

SOURCE_FILES = Rake::FileList.new('fnl/**/*.fnl') + ['init.fnl']
TARGET_FILES = SOURCE_FILES.pathmap('%{^fnl/,lua/}X.lua')

task default: TARGET_FILES
CLEAN.include(TARGET_FILES)

directory 'lua'

rule '.lua' => [->(f) { source_for_lua(f) }, 'lua'] do |t|
  mkdir_p t.name.pathmap('%d')
  sh "fennel --compile #{t.source} > #{t.name}"
end

def source_for_lua(lua_file)
  SOURCE_FILES.find { |f| f.ext('') == lua_file.pathmap('%{^lua/,fnl/}X') }
end
