require 'rake/clean'

SOURCE_FILES = Rake::FileList.new('fnl/**/*.fnl', '*.fnl')
TARGET_FILES = SOURCE_FILES.pathmap('%{^fnl/,lua/}X.lua').add('lua/lume.lua')

task default: TARGET_FILES
CLEAN.include(TARGET_FILES)

directory 'lua'

rule 'lume.lua' do
  sh "curl -Ls https://raw.githubusercontent.com/rxi/lume/98847e7812cf28d3d64b289b03fad71dc704547d/lume.lua -o lua/lume.lua"
end

rule '.lua' => [->(f) { source_for_lua(f) }, 'lua'] do |t|
  ensure_dir t.name.pathmap('%d')
  sh "fennel --compile #{t.source} > #{t.name}"
end

def source_for_lua(lua_file)
  SOURCE_FILES.find { |f| f.ext('') == lua_file.pathmap('%{^lua/,fnl/}X') }
end

def ensure_dir(path)
  mkdir_p path unless Dir.exists? path
end
