#!/usr/bin/env sh

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autoraise
yabai -m config window_placement            second_child
yabai -m config window_topmost              on
yabai -m config window_shadow               float
yabai -m config window_opacity              on
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config window_border               off
yabai -m config window_border_width         2
yabai -m config active_window_border_color  0xff859900
yabai -m config normal_window_border_color  0xff002b36
yabai -m config insert_feedback_color       0xffd75f5f
yabai -m config split_ratio                 0.61803
yabai -m config auto_balance                off
yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

yabai -m config layout                      bsp
yabai -m config top_padding                 6
yabai -m config left_padding                6
yabai -m config bottom_padding              6
yabai -m config right_padding               6
yabai -m config window_gap                  6

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Stats$" manage=off

echo "yabai configuration loaded..."
