I manage my dotfiles using [[https://github.com/twpayne/chezmoi][chezmoi]].

This repo includes configs for macOS and my riced up [[https://i3wm.org/][i3]] (I use [[https://archlinux.org/][arch]] btw...)

I mainly use [[https://github.com/hlissner/doom-emacs][Doom]] [[https://www.gnu.org/software/emacs/][Emacs]], but I also maintain my [[https://neovim.io/][Neovim]] configured with some
bling just in case I need to pop up an editor for a quick edit in the terminal.
Speaking of the terminal, I use [[https://github.com/alacritty/alacritty][alacritty]]. It's fast. In it, I live at all times
inside [[https://github.com/tmux/tmux][tmux]].

To configure neovim I use [[https://fennel-lang.org/][fennel]]. In order to compile fennel whenever a source
changes, I use a little [[https://www.chezmoi.io/docs/reference/#source-state-attributes][chezmoi hook]] [[https://github.com/joaofnds/dotfiles/blob/e37fdc37ed2da3f5f1c4c5972da135e4b83824dd/dot_config/nvim/run_once_after_compile_fennel.tmpl#L3][hack]] to run a [[https://github.com/joaofnds/dotfiles/blob/e37fdc37ed2da3f5f1c4c5972da135e4b83824dd/dot_config/nvim/Rakefile][Rakefile]].

I use [[https://ethanschoonover.com/solarized/][solarized]] on almost everything.

* shoutouts
- [[https://github.com/tmux/tmux][tmux/tmux: terminal multiplexer]]
- [[https://github.com/junegunn/fzf][junegunn/fzf: A command-line fuzzy finder]]
- [[https://github.com/sharkdp/fd][sharkdp/fd: A simple, fast and user-friendly alternative to 'find']]
- [[https://github.com/eradman/entr][eradman/entr: Run arbitrary commands when files change]]
- [[https://github.com/chmln/sd][chmln/sd: Intuitive find & replace CLI (sed alternative)]]
- [[https://github.com/ggreer/the_silver_searcher][ggreer/the_silver_searcher: A code-searching tool similar to ack, but faster.]]
- [[https://github.com/sachaos/viddy][sachaos/viddy: Modern watch command]]
- [[https://github.com/theryangeary/choose][theryangeary/choose: A human-friendly and fast alternative to cut and (sometimes) awk]]
- [[https://github.com/jhspetersson/fselect][jhspetersson/fselect: Find files with SQL-like queries]]
- [[https://github.com/BurntSushi/xsv][BurntSushi/xsv: A fast CSV command line toolkit written in Rust.]]
- [[https://github.com/mgdm/htmlq][mgdm/htmlq: Like jq, but for HTML]]

** files
*** sync
- [[https://github.com/wayned/rsync][wayned/rsync: fast incremental file transfer]]
- [[https://github.com/rclone/rclone][rclone/rclone: rsync for cloud storage]]
- [[https://github.com/twpayne/chezmoi][twpayne/chezmoi: Manage your dotfiles across multiple diverse machines, securely.]]

*** share
**** local network
- [[https://github.com/schollz/croc][schollz/croc]]
- [[https://github.com/robinlinus/snapdrop][robinlinus/snapdrop: local file sharing in your browser. Inspired by Apple's Airdrop]]

**** internet
- [[https://github.com/sniptt-official/ots][sniptt-official/ots: share end-to-end encrypted secrets with others via a one-time url]]
- [[https://wormhole.app/][Wormhole - share files with e2e encryption and a link that automatically expires]]

* Keyboard
I use a [[https://www.zsa.io/moonlander][ZSA Moonlander]], you can find (and fork) [[https://configure.zsa.io/moonlander/layouts/ZQX76][my layout on Oryx]]
