#!/usr/bin/env zsh

if lima nerdctl &>/dev/null; then
    lima nerdctl "$@"
elif [ -S $HOME/Library/Containers/com.docker.docker/Data/docker-cli.sock ]; then
    DOCKER_EXEC=$(whereis -abq docker | cut -d' ' -f 2)
    $DOCKER_EXEC "$@"
else
    echo "neither lima nor docker is running."
    exit 1
fi
