#!/usr/bin/env zsh

if [ -S $HOME/.lima/default/ga ]; then
    lima nerdctl "$@"
elif [ -S $HOME/.docker/run/docker.sock ]; then
    DOCKER_EXEC=$(whereis -abq docker | cut -d' ' -f 2)
    $DOCKER_EXEC "$@"
else
    echo "neither lima nor docker is running."
    exit 1
fi
