[settings]
env_shell_expand = true

[env]
MISE_GO_DEFAULT_PACKAGES_FILE = "$HOME/.config/mise/default-packages/go"
MISE_NODE_DEFAULT_PACKAGES_FILE = "$HOME/.config/mise/default-packages/node"
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "$HOME/.config/mise/default-packages/python"
MISE_RUBY_DEFAULT_PACKAGES_FILE = "$HOME/.config/mise/default-packages/ruby"

[tools]
babashka = "latest"
bun = "latest"
clojure = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
gitleaks = "latest"
gleam = "latest"
go = "latest"
java = "latest"
nodejs = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
task = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
zig = "latest"

"npm:depcheck" = "latest"
"npm:lua-fmt" = "latest"
"npm:npm-check-updates" = "latest"
"npm:vmd" = "latest"
"npm:zx" = "latest"
