[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = 'shell "open -R \"$1\""'
desc = "Reveal in Finder"
