return {
	"christoomey/vim-tmux-runner",
	cmd = {
		"VtrOpenRunner",
		"VtrSendCtrlC",
		"VtrSendCtrlD",
		"VtrFlushCommand",
		"VtrResizeRunner",
		"VtrAttachToPane",
		"VtrClearRunner",
		"VtrDetachRunner",
		"VtrFocusRunner",
		"VtrKillRunner",
		"VtrSendLinesToRunner",
		"VtrReorientRunner",
		"VtrSendCommandToRunner",
	},
	keys = {
		{ "<leader>x-", ':VtrOpenRunner { "orientation": "v", "percentage": 50 }<cr>', desc = "open vertical runner" },
		{ "<leader>x=", ':VtrOpenRunner { "orientation": "h", "percentage": 50  }<cr>', desc = "open horizontal runner" },
		{ "<leader>xC", "<cmd>VtrSendCtrlC<cr>", desc = "send ctrl-c" },
		{ "<leader>xD", "<cmd>VtrSendCtrlD<cr>", desc = "send ctrl-d" },
		{ "<leader>xF", "<cmd>VtrFlushCommand<cr>", desc = "flush command" },
		{ "<leader>xR", "<cmd>VtrResizeRunner<cr>", desc = "resize" },
		{ "<leader>xa", "<cmd>VtrAttachToPane<cr>", desc = "attach" },
		{ "<leader>xc", "<cmd>VtrClearRunner<cr>", desc = "clear runner" },
		{ "<leader>xd", "<cmd>VtrDetachRunner<cr>", desc = "detach runner" },
		{ "<leader>xf", "<cmd>VtrFocusRunner<cr>", desc = "focus runner" },
		{ "<leader>xk", "<cmd>VtrKillRunner<cr>", desc = "kill runner" },
		{ "<leader>xl", "<cmd>VtrSendLinesToRunner<cr>", desc = "send lines" },
		{ "<leader>xo", "<cmd>VtrReorientRunner<cr>", desc = "reorient" },
		{ "<leader>xr", "<cmd>VtrSendCommandToRunner<cr>", desc = "send command" },
		{ "<leader>xl", ":VtrSendLinesToRunner<cr>", desc = "send lines", mode = "v" },
	},
}
