return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	init = function()
		-- undo breakpoints
		for _, c in ipairs({ ",", ".", ";", "(", "[", "{" }) do
			vim.keymap.set("i", c, c .. "<c-g>u")
		end
	end,
	config = function()
		local wk = require("which-key")
		wk.setup({ icons = { mappings = false } })
		wk.add({
			{ "g", group = "go to" },
			{ "Q", "<nop>", desc = "nop" },
			{ "zj", ":lua require('leap').leap({})<cr>", desc = "leap forward" },
			{
				"zk",
				":lua require('leap').leap({backward = true})<cr>",
				desc = "leap backward",
			},
			{ "]", group = "next" },
			{ "[", group = "previous" },
			{ "<esc>", "<esc>:nohl<CR><esc>", desc = "esc" },
			{ "<leader>", group = "leader" },
			{ "<leader>?", wk.show, desc = "show" },
			{
				"<leader><leader>",
				":FzfLua files<cr>",
				desc = "find files: searches whole project for a file",
			},
			{
				"<leader>.",
				":FzfLua files cwd=%:p:h<cr>",
				desc = "search for a file in the current directory",
			},
			{ "<leader>w", group = "window" },
			{ "<leader>w-", ":wincmd _<cr>:wincmd |<cr>", desc = "zoom in" },
			{ "<leader>w=", ":wincmd =<cr>", desc = "re-balance windows" },
			{ "<leader>w_", ":wincmd _<cr>", desc = "max out the height" },
			{ "<leader>w|", ":wincmd |<cr>", desc = "max out the width" },
			{ "<leader>wN", ":new<cr>", desc = "new empty window" },
			{ "<leader>wV", ":vnew<cr>", desc = "new vertical empty window" },
			{ "<leader>ws", ":sp<cr>", desc = "open a horizontal split" },
			{ "<leader>wv", ":vsp<cr>", desc = "open a vertical split" },
			{ "<leader>wq", ":q<cr>", desc = "close current window" },
			{ "<leader>wB", ":wincmd T<cr>", desc = "break out split into window" },
			{ "<leader>wo", ":wincmd o<cr>", desc = "kill other windows" },
			{ "<leader>wr", ":wincmd r<cr>", desc = "swaps windows" },
			{ "<leader>wh", ":wincmd h<cr>", desc = "moves the cursor buffer on the left" },
			{
				"<leader>wj",
				":wincmd j<cr>",
				desc = "moves the cursor buffer on the bottom",
			},
			{ "<leader>wk", ":wincmd k<cr>", desc = "moves the cursor buffer on the top" },
			{
				"<leader>wl",
				":wincmd l<cr>",
				desc = "moves the cursor buffer on the right",
			},
			{ "<leader>wH", ":wincmd H<cr>", desc = "moves buffer to the left" },
			{ "<leader>wJ", ":wincmd J<cr>", desc = "moves the buffer to the bottom" },
			{ "<leader>wK", ":wincmd K<cr>", desc = "moves the buffer to the top" },
			{ "<leader>wL", ":wincmd L<cr>", desc = "moves cursor buffer to the right" },
			{ "<leader>f", group = "file" },
			{ "<leader>ft", ":vsplit ~/TODO.md<cr>", desc = "opens TODO.md" },
			{ "<leader>fs", ":w<cr>", desc = "writes the buffer" },
			{ "<leader>fr", ":FzfLua oldfiles<cr>", desc = "recent" },
			{ "<leader>g", group = "git" },
			{ "<leader>gP", ":Gitsigns preview_hunk<cr>", desc = "preview hunk" },
			{ "<leader>gS", ":Gitsigns stage_buffer<cr>", desc = "stage buffer" },
			{ "<leader>gX", ":Gitsigns reset_buffer<cr>", desc = "discard buffer" },
			{ "<leader>gb", ":Gitsigns toggle_current_line_blame<cr>", desc = "blame" },
			{ "<leader>gd", ":Gitsigns diffthis<cr>", desc = "diff" },
			{ "<leader>gg", ":Neogit<cr>", desc = "neogit" },
			{ "<leader>gl", ":Gitsigns toggle_linehl<cr>", desc = "line diff" },
			{ "<leader>gn", ":Gitsigns next_hunk<CR>", desc = "next hunk" },
			{ "<leader>gp", ":Gitsigns prev_hunk<CR>", desc = "previous hunk" },
			{ "<leader>gs", ":Gitsigns stage_hunk<cr>", desc = "stage hunk" },
			{ "<leader>gt", ":Tardis<CR>", desc = "time machine" },
			{ "<leader>gv", ":Gitsigns select_hunk<cr>", desc = "select hunk" },
			{ "<leader>gx", ":Gitsigns reset_hunk<cr>", desc = "discard hunk" },
			{ "<leader>gf", group = "find" },
			{ "<leader>gff", ":FzfLua git_files<cr>", desc = "git files" },
			{ "<leader>gfs", ":FzfLua git_status<cr>", desc = "status files" },
			{ "<leader>gfc", ":FzfLua git_commits<cr>", desc = "commits" },
			{ "<leader>gfC", ":FzfLua git_bcommits<cr>", desc = "buffer commits" },
			{ "<leader>h", group = "help" },
			{
				"<leader>hu",
				function()
					require("jf").update()
				end,
				desc = "update",
			},
			{ "<leader>s", group = "search" },
			{ "<leader>sb", ":FzfLua buffers<cr>", desc = "buffers" },
			{ "<leader>sf", ":FzfLua files<cr>", desc = "files" },
			{ "<leader>sm", ":FzfLua marks<cr>", desc = "marks" },
			{ "<leader>sp", ":FzfLua live_grep<cr>", desc = "search project" },
			{ "<leader>b", group = "buffers" },
			{ "<leader>bb", ":FzfLua buffers<cr>", desc = "search buffers" },
			{ "<leader>bp", ":BufferPrevious<cr>", desc = "previous" },
			{ "<leader>bn", ":BufferNext<cr>", desc = "next" },
			{ "<leader>bs", ":BufferPick<cr>", desc = "search" },
			{ "<leader>b<", ":BufferMovePrevious<cr>", desc = "move previous" },
			{ "<leader>b>", ":BufferMoveNext<cr>", desc = "move next" },
			{ "<leader>b1", ":BufferGoto 1<CR>", desc = "goto 1" },
			{ "<leader>b2", ":BufferGoto 2<CR>", desc = "goto 2" },
			{ "<leader>b3", ":BufferGoto 3<CR>", desc = "goto 3" },
			{ "<leader>b4", ":BufferGoto 4<CR>", desc = "goto 4" },
			{ "<leader>b5", ":BufferGoto 5<CR>", desc = "goto 5" },
			{ "<leader>b6", ":BufferGoto 6<CR>", desc = "goto 6" },
			{ "<leader>b7", ":BufferGoto 7<CR>", desc = "goto 7" },
			{ "<leader>b8", ":BufferGoto 8<CR>", desc = "goto 8" },
			{ "<leader>b9", ":BufferLast<CR>", desc = "goto last" },
			{ "<leader>bk", ":BufferClose<cr>", desc = "kill" },
			{ "<leader>bd", group = "delete" },
			{ "<leader>bdd", ":BufferClose<cr>", desc = "current" },
			{ "<leader>bda", ":BufferWipeout<cr>", desc = "all" },
			{ "<leader>bdo", ":BufferCloseAllButCurrent<cr>", desc = "others" },
			{ "<leader>bdl", ":BufferCloseBuffersLeft<cr>", desc = "left" },
			{ "<leader>bdr", ":BufferCloseBuffersRight<cr>", desc = "right" },
			{ "<leader>o", group = "open" },
			{ "<leader>oP", ":MarkdownPreviewToggle<cr>", desc = "Toggle markdown preview" },
			{ "<leader>o.", ":Yazi<cr>", desc = "Yazi here" },
			{ "<leader>oy", ":Yazi toggle<cr>", desc = "Yazi toggle" },
			{ "<leader>oY", ":Yazi cwd<cr>", desc = "Yazi cwd" },
			{ "<leader>p", group = "project" },
			{ "<leader>pr", ":FzfLua oldfiles cwd=%:p:h<cr>", desc = "recent files" },
			{ "<leader>c", group = "code" },
			{ "<leader>cl", group = "lsp" },
			{ "<leader>cls", ":LspStart<cr>", desc = "start" },
			{ "<leader>clS", ":LspStop<cr>", desc = "stop" },
			{ "<leader>t", group = "toggle" },
			{ "<leader>tc", ":TSContextToggle<cr>", desc = "toggle context" },
			{ "<leader>ti", ":set invlist<cr>", desc = "invisible chars" },
			{ "<leader>tj", ":TSJToggle<cr>", desc = "split join" },
			{ "<leader>tl", ":set relativenumber!<cr>", desc = "relative number" },
			{ "<leader>tu", ":UndotreeToggle<cr>", desc = "undo tree" },
			{ "<leader>tw", ":set wrap!<cr>", desc = "toggle wrap" },
			{ "<leader>x", group = "tmux" },
			{
				"<leader>x-",
				':VtrOpenRunner { "orientation": "v", "percentage": 50 }<cr>',
				desc = "open vertical runner",
			},
			{
				"<leader>x=",
				':VtrOpenRunner { "orientation": "h", "percentage": 50  }<cr>',
				desc = "open horizontal runner",
			},
			{ "<leader>xC", ":VtrSendCtrlC<cr>", desc = "send ctrl-c" },
			{ "<leader>xD", ":VtrSendCtrlD<cr>", desc = "send ctrl-d" },
			{ "<leader>xF", ":VtrFlushCommand<cr>", desc = "flush command" },
			{ "<leader>xR", ":VtrResizeRunner<cr>", desc = "resize" },
			{ "<leader>xa", ":VtrAttachToPane<cr>", desc = "attach" },
			{ "<leader>xc", ":VtrClearRunner<cr>", desc = "clear runner" },
			{ "<leader>xd", ":VtrDetachRunner<cr>", desc = "detach runner" },
			{ "<leader>xf", ":VtrFocusRunner<cr>", desc = "focus runner" },
			{ "<leader>xk", ":VtrKillRunner<cr>", desc = "kill runner" },
			{ "<leader>xl", ":VtrSendLinesToRunner<cr>", desc = "send lines" },
			{ "<leader>xo", ":VtrReorientRunner<cr>", desc = "reorient" },
			{ "<leader>xr", ":VtrSendCommandToRunner<cr>", desc = "send command" },
			{ "<c-j>", ":m '>+1<cr>gv=gv", desc = "move line down", mode = "v" },
			{ "<c-k>", ":m '<-2<cr>gv=gv", desc = "move line up", mode = "v" },
			{ "gb", group = "base64", mode = "v" },
			{ "gbe", 'c<c-r>=trim(system("base64", @"))<cr><esc>', desc = "encode", mode = "v" },
			{ "gbd", 'c<c-r>=system("base64 --decode", @"))<cr><esc>', desc = "decode", mode = "v" },
			{ "gt", 'c<c-r>=strftime("%Y-%m-%dT%H:%M:%S%z", @")[0:9])<cr><esc>', desc = "encode", mode = "v" },
			{ "<leader>x", group = "tmux", mode = "v" },
			{ "<leader>xl", ":VtrSendLinesToRunner<cr>", desc = "send lines", mode = "v" },
		})
	end,
}
