(require :settings)
(vim.cmd "source ~/.config/nvim/plug.vim")
(require :keybinds)
(require :config.saga)
(let [lsp-config (require :config.lsp)]
  (lsp-config.init))
(require :config.telescope)
(require :config.which-key)
(require :config.treesitter)
(require :config.vim-tmux-runner)
(require :config.gitgutter)
(require :config.easy-align)
