{ pkgs, ... }:
{
  environment.systemPackages = [
    pkgs.agent-browser
    pkgs.aspell
    pkgs.bat
    pkgs.btop
    pkgs.chezmoi
    pkgs.cowsay
    pkgs.curl
    pkgs.delta
    pkgs.dust
    pkgs.emacs
    pkgs.entr
    pkgs.fd
    pkgs.ffmpeg
    pkgs.flyctl
    pkgs.fzf
    pkgs.gemini-cli
    pkgs.gh
    pkgs.git
    pkgs.gnupg
    pkgs.go-task
    pkgs.hexyl
    pkgs.hyperfine
    pkgs.imagemagick
    pkgs.jq
    pkgs.lua
    pkgs.mise
    pkgs.neovim
    pkgs.nixfmt
    pkgs.opencode
    pkgs.pinentry_mac
    pkgs.ripgrep
    pkgs.rtk
    pkgs.sd
    pkgs.silver-searcher
    pkgs.sqlite
    pkgs.starship
    pkgs.tmux
    pkgs.tokei
    pkgs.tree
    pkgs.tree-sitter
    pkgs.typos
    pkgs.viddy
    pkgs.yazi
    pkgs.zoxide
  ];
}
