#!/usr/bin/env sh

docker run \
	-d \
	--cgroupns host \
	--pid host \
	--name dd-agent \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-v /proc/:/host/proc/:ro \
	-v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
	-e DD_API_KEY="$1" \
	gcr.io/datadoghq/agent:7
