#!/usr/bin/env sh

if [ -z "$1" ]; then
	echo "No argument supplied"
	exit 1
fi

docker run -d --name dd-agent \
	-e DD_API_KEY="$1" \
	-e DD_SITE="datadoghq.com" \
	-e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true \
	-e DD_APM_ENABLED=true \
	-e DD_APM_NON_LOCAL_TRAFFIC=true \
	-e DD_SYSTEM_PROBE_ENABLED=true \
	-e DD_APM_RECEIVER_SOCKET=/opt/datadog/apm/inject/run/apm.socket \
	-e DD_DOGSTATSD_SOCKET=/opt/datadog/apm/inject/run/dsd.socket \
	-v /opt/datadog/apm:/opt/datadog/apm \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-v /proc/:/host/proc/:ro \
	-v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
	-v /var/lib/docker/containers:/var/lib/docker/containers:ro \
	gcr.io/datadoghq/agent:7
