#!/usr/bin/env ruby

require 'date'

if ARGV.length != 2
  puts <<~EOS
    please provide a start and stop date. Ex:
    $ ruby this_script.rb 10-08-2021 28-11-2021
  EOS
  exit 1
end

start = Date.parse(ARGV[0])
stop = Date.parse(ARGV[1])

unless start < stop
  puts 'start must be before stop'
  exit 1
end

def week_start(date)
  date - (date.wday - 1) % 7
end

curr = week_start(start)
i = 1

while curr < stop
  from = curr     # monday
  to   = curr + 5 # friday

  puts "semana #{i} (#{from} - #{to})"

  curr += 7
  i    += 1
end
