#!/usr/bin/env sh

fd --hidden \
  --prune \
  --no-ignore \
  --exclude '.vscode' \
  --exclude '.config' \
  --exclude '.local' \
  --exclude '.npm' \
  --exclude '.nodenv' \
  --type directory \
  --fixed-strings \
  node_modules \
  --exec du {} \
| sort -rnk1 \
| awk '{ print $2 }' \
| xargs du -sh \
| fzf -m \
| awk '{ print $2 }' \
| xargs -p -n1 rm -rf
