#!/usr/bin/env zsh

EMACS_HOME="$HOME/.config/emacs"
RESTIC_HOME="$HOME/.config/restic"

set_restic_vars() {
	if [[ -z $RESTIC_REPOSITORY ]]; then
		export RESTIC_REPOSITORY=$(gpg --decrypt $RESTIC_HOME/resticrepo.gpg)
	fi

	if [[ -z $RESTIC_PASSWORD_COMMAND ]]; then
		export RESTIC_PASSWORD_COMMAND="gpg -d $RESTIC_HOME/resticpass.gpg"
	fi
}

backup() {
	set_restic_vars
	restic backup --verbose "$EMACS_HOME/.local/elfeed"
}

restore() {
	set_restic_vars
	restic restore latest --path "$EMACS_HOME/.local/elfeed" --target /
}

help() {
	cat <<__EOF__
usage: elfeed [backup | restore]
__EOF__
}

case $1 in
backup)
	backup
	;;
restore)
	restore
	;;
*)
	help
	;;
esac
