#!/usr/bin/env ruby

class ASDF
  class << self
    def plugin_list
      `asdf plugin-list`.split("\n")
    end

    def list(plugin)
      `asdf list #{plugin}`.split("\n")
    end

    def install_latest(plugin)
      `asdf install #{plugin} latest`
    end

    def set_global(plugin, version)
      `asdf global #{plugin} #{version}`
    end
  end
end

class Plugin
  attr_reader :name

  alias to_s name

  private

  def initialize(plugin_name)
    @name = plugin_name
  end
end

class PluginManager
  def update_to_latest
    install_latest
    set_global_to_latest
  end

  private

  def install_latest
    puts "[#{plugin}] installing latest version"
    ASDF.install_latest(plugin.name)
  end

  def set_global_to_latest
    latest_version = ASDF.list(plugin.name).last
    puts "[#{plugin}] setting global version to #{latest_version}"
    ASDF.set_global(plugin.name, latest_version)
  end

  attr_reader :plugin

  def initialize(plugin)
    @plugin = plugin
  end
end

ASDF.plugin_list.map do |plugin_name|
  Ractor.new plugin_name do |plugin_name|
    plugin = Plugin.new(plugin_name)
    PluginManager.new(plugin).update_to_latest
  end
end.each(&:take)
