#!/usr/bin/env sh

fd --hidden \
  --prune \
  --no-ignore \
  --exclude '.vscode' \
  --exclude '.config' \
  --exclude '.local' \
  --exclude '.npm' \
  --exclude '.nodenv' \
  --type directory \
  node_modules \
  --exec-batch du -sh \
| sort --reverse --human-numeric-sort \
| fzf --multi \
| awk -F'\t' '{ print $2 }' \
| tr '\n' '\0' \
| xargs -0 -p -n1 rm -rf
