#!/usr/bin/env bash

CACHE="$HOME/.cache/fleet"

function versions() {
	curl -s "https://data.services.jetbrains.com/products?code=FL&latest=true" |
		jq -r '.[].releases[] | .date+": "+.version'
}

function store() {
	versions >"$CACHE"
}

function diff() {
	TEMP=$(mktemp)
	versions >"$TEMP"
	delta "$CACHE" "$TEMP"
	rm "$TEMP"
}

case $1 in
store)
	store
	;;
*)
	diff
	;;
esac
