#!/usr/bin/env zsh

set_restic_vars() {
	if [[ -z $RESTIC_REPOSITORY ]]; then
		export RESTIC_REPOSITORY=$(gpg --decrypt $HOME/.config/restic/resticrepo.gpg)
	fi

	if [[ -z $RESTIC_PASSWORD_COMMAND ]]; then
		export RESTIC_PASSWORD_COMMAND="gpg -d $HOME/.config/restic/resticpass.gpg"
	fi
}

backup() {
	set_restic_vars
	restic backup --verbose "$HOME/.emacs.d/.local/elfeed"
}

restore() {
	set_restic_vars
	restic restore latest --path "$HOME/.emacs.d/.local/elfeed" --target /
}

help() {
	cat <<__EOF__
usage: elfeed [backup | restore]
__EOF__
}

case $1 in
backup)
	backup
	;;
restore)
	restore
	;;
*)
	help
	;;
esac
