#!/usr/bin/env ruby

SEMVER_FORMAT = /^\d+(\.\d+){1,2}$/

plugin_filter = {
  "java": /openjdk/,
  "clojure": //,
  "erlang": SEMVER_FORMAT,
  "elixir": SEMVER_FORMAT,

  "deno": SEMVER_FORMAT,
  "direnv": SEMVER_FORMAT,
  "elm": SEMVER_FORMAT,
  "gcloud": SEMVER_FORMAT,
  "github-cli": SEMVER_FORMAT,
  "golang": SEMVER_FORMAT,
  "haskell": SEMVER_FORMAT,
  "nodejs": SEMVER_FORMAT,
  "postgres": SEMVER_FORMAT,
  "python": SEMVER_FORMAT,
  "redis": SEMVER_FORMAT,
  "ruby": SEMVER_FORMAT,
  "rust": SEMVER_FORMAT,
  "shellcheck": SEMVER_FORMAT,
  "terraform": SEMVER_FORMAT,
  "tfsec": SEMVER_FORMAT
}

def install_plugin(plugin, format)
  `asdf plugin-add #{plugin}`

  latest_version = `asdf list-all #{plugin}`.split("\n").grep(format).last

  if latest_version.nil?
    puts "could not find latest version for #{plugin}"
  else
    puts "installing #{plugin}: #{latest_version}"
    `asdf install #{plugin} #{latest_version}`

    puts "setting asdf global #{plugin} to #{latest_version}"
    `asdf global #{plugin} #{latest_version}`
  end
end

plugin_filter.each(&method(:install_plugin))
